# Generated by Django 5.0 on 2023-12-25 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company", "0004_myowntoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartexModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=10, verbose_name="نام کالا")),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_st", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.usermodel",
                        verbose_name="کارمند",
                    ),
                ),
            ],
            options={
                "verbose_name": "شماره تماس ",
                "verbose_name_plural": " شماره تماس ها",
            },
        ),
    ]
