# Generated by Django 5.0 on 2023-12-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cartex", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartexmodel",
            options={
                "verbose_name": "کارتکس انبار",
                "verbose_name_plural": "کارتکس های انبار",
            },
        ),
        migrations.AlterField(
            model_name="cartexmodel",
            name="title",
            field=models.CharField(max_length=50, verbose_name="نام کالا"),
        ),
    ]
