# Generated by Django 5.0 on 2024-01-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cartex", "0002_alter_cartexmodel_options_alter_cartexmodel_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartexmodel",
            name="is_always",
            field=models.BooleanField(default=False, verbose_name="دایم"),
        ),
        migrations.AddField(
            model_name="cartexmodel",
            name="is_temporary",
            field=models.BooleanField(default=False, verbose_name="موقت"),
        ),
    ]
