# Generated by Django 5.0 on 2024-01-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cartex", "0003_cartexmodel_is_always_cartexmodel_is_temporary"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartexmodel",
            name="is_back",
            field=models.BooleanField(default=False, verbose_name="برگشت کالا"),
        ),
    ]
