# Generated by Django 5.0 on 2024-01-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cartex", "0004_cartexmodel_is_back"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartexmodel",
            name="is_manager",
            field=models.BooleanField(default=False, verbose_name="تایید ادمین"),
        ),
    ]
