# Generated by Django 5.0 on 2023-12-16 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='نام')),
                ('last_name', models.CharField(max_length=30, verbose_name=' نام خانوادگی')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='شماره موبایل')),
                ('post', models.CharField(blank=True, max_length=20, null=True, verbose_name='سمت')),
                ('is_driver', models.BooleanField(default=False, verbose_name='آیا راننده است ؟')),
                ('is_admin', models.BooleanField(default=False, verbose_name='آیا دسترسی ادمین دارد ؟')),
                ('password', models.CharField(max_length=20, verbose_name='رمز')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'کارمندان',
                'verbose_name_plural': 'کارمند',
            },
        ),
        migrations.CreateModel(
            name='DriverModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='company.usermodel', verbose_name='راننده')),
                ('users', models.ManyToManyField(related_name='user', to='company.usermodel', verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'راننده ها',
                'verbose_name_plural': 'راننده',
            },
        ),
    ]
