# Generated by Django 5.0 on 2023-12-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drivermodel',
            options={'verbose_name': 'راننده ', 'verbose_name_plural': ' راننده ها'},
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'کارمند', 'verbose_name_plural': 'کارمندان'},
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_tell',
            field=models.BooleanField(default=False, verbose_name='آیا به بخش شماره تلفن ها دسترسی دارد ؟'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='is_driver',
            field=models.BooleanField(default=False, verbose_name='آیا به بخش راننده ها دسترسی دارد ؟'),
        ),
    ]
