# Generated by Django 5.0 on 2023-12-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_drivermodel_options_alter_usermodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_driver_role',
            field=models.BooleanField(default=False, verbose_name='آیا به بخش راننده ها دسترسی دارد ؟'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='is_driver',
            field=models.BooleanField(default=False, verbose_name='آیا راننده است ؟'),
        ),
    ]
