# Generated by Django 5.0 on 2023-12-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0004_myowntoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="is_pm",
            field=models.BooleanField(
                default=False, verbose_name="آیا به بخش پی ام دسترسی دارد ؟"
            ),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="is_scan",
            field=models.BooleanField(
                default=False, verbose_name="آیا به بخش بارکد خوان دسترسی دارد ؟"
            ),
        ),
    ]
