# Generated by Django 5.0 on 2023-12-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0005_usermodel_is_pm_usermodel_is_scan"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="company_code",
            field=models.CharField(
                default=10, max_length=10, unique=True, verbose_name="کد پرسنلی"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="is_tell",
            field=models.BooleanField(
                default=True, verbose_name="آیا به بخش شماره تلفن ها دسترسی دارد ؟"
            ),
        ),
    ]
