# Generated by Django 5.0 on 2023-12-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0007_alter_usermodel_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="company_code",
            field=models.CharField(max_length=10, verbose_name="کد پرسنلی"),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="phone_number",
            field=models.CharField(
                max_length=11, unique=True, verbose_name="شماره موبایل"
            ),
        ),
    ]
