# Generated by Django 5.0 on 2024-01-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0008_alter_usermodel_company_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="is_cartex",
            field=models.BooleanField(
                default=True, verbose_name="آیا به بخش کارتکس انبار دسترسی دارد ؟"
            ),
        ),
    ]
