# Generated by Django 5.0 on 2024-01-05 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0009_usermodel_is_cartex"),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("R", "Return"), ("W", "Went")],
                        max_length=1,
                        verbose_name="مسیر",
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "user_driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.drivermodel",
                        verbose_name="راننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "مسیر ",
                "verbose_name_plural": " مسیر ها",
            },
        ),
    ]
