# Generated by Django 5.0 on 2024-01-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0011_drivermodel_direction_delete_directionmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoneyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "money_driver",
                    models.CharField(max_length=7, verbose_name="مبلغ راننده"),
                ),
                (
                    "money_user",
                    models.CharField(max_length=7, verbose_name="مبلغ مسافر"),
                ),
            ],
            options={
                "verbose_name": "مبلغ ",
                "verbose_name_plural": " مبلغ ها",
            },
        ),
        migrations.AddField(
            model_name="drivermodel",
            name="money",
            field=models.CharField(default="", max_length=6),
            preserve_default=False,
        ),
    ]
