# Generated by Django 5.0 on 2024-01-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0012_moneymodel_drivermodel_money"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drivermodel",
            name="money",
        ),
        migrations.AddField(
            model_name="drivermodel",
            name="all_money",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="drivermodel",
            name="driver_money",
            field=models.CharField(default="", max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="drivermodel",
            name="user_money",
            field=models.CharField(default="", max_length=7),
            preserve_default=False,
        ),
    ]
