# Generated by Django 5.0 on 2024-01-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0013_remove_drivermodel_money_drivermodel_all_money_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="drivermodel",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="تاییدیه"),
        ),
    ]
