# Generated by Django 5.0 on 2024-01-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0015_drivermodel_is_accept"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="is_store_manager",
            field=models.BooleanField(
                default=False, verbose_name="آیا به بخش مدیریت انبار دسترسی دارد ؟"
            ),
        ),
    ]
