# Generated by Django 5.0.1 on 2024-01-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_usermodel_is_store_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='agency',
            field=models.BooleanField(default=False, verbose_name='آیا به بخش آزانس دسترسی دارد ؟'),
        ),
    ]
