# Generated by Django 5.0.1 on 2024-01-29 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_usermodel_agency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='agency',
            new_name='is_agency',
        ),
    ]
