# Generated by Django 5.0 on 2023-12-27 18:42

import pm.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PmObjectModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80, verbose_name="نام")),
                (
                    "isbn",
                    models.CharField(
                        help_text="کالا کد", max_length=13, verbose_name="ISBN"
                    ),
                ),
                (
                    "barcode",
                    models.ImageField(
                        blank=True,
                        help_text="به این قسمت کاری نداشته باشید",
                        null=True,
                        upload_to=pm.models.news_barcode_path,
                    ),
                ),
            ],
        ),
    ]
