# Generated by Django 5.0.1 on 2024-01-29 09:40

import django.db.models.deletion
import pm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceEngineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام دستگاه یا موتور')),
            ],
            options={
                'verbose_name': 'دستگاه و موتور',
                'verbose_name_plural': 'دستگاه ها و موتور ها',
            },
        ),
        migrations.CreateModel(
            name='UnitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='نام واحد')),
            ],
            options={
                'verbose_name': 'واحد',
                'verbose_name_plural': 'واحد ها',
            },
        ),
        migrations.CreateModel(
            name='PmObjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(help_text='کالا کد', max_length=13, verbose_name='شناسه بارکد')),
                ('barcode', models.ImageField(blank=True, help_text='به این قسمت کاری نداشته باشید', null=True, upload_to=pm.models.news_barcode_path, verbose_name='عکس')),
                ('location', models.CharField(max_length=50, verbose_name='محل استقرار')),
                ('country_maker', models.CharField(blank=True, max_length=50, null=True, verbose_name='کشور سازنده')),
                ('company_maker', models.CharField(blank=True, max_length=50, null=True, verbose_name='شرکت سازنده')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.deviceenginemodel', verbose_name='دستگاه')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.unitmodel', verbose_name='واحد استقرار')),
            ],
            options={
                'verbose_name': 'دستگاه صنعتی',
                'verbose_name_plural': 'دستگاه های صنعتی',
            },
        ),
    ]
