# Generated by Django 5.0 on 2023-12-27 19:24

import pm.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pm", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pmobjectmodel",
            options={
                "verbose_name": "دستگاه صنعتی",
                "verbose_name_plural": "دستگاه های صنعتی",
            },
        ),
        migrations.AlterField(
            model_name="pmobjectmodel",
            name="barcode",
            field=models.ImageField(
                blank=True,
                help_text="به این قسمت کاری نداشته باشید",
                null=True,
                upload_to=pm.models.news_barcode_path,
                verbose_name="عکس",
            ),
        ),
        migrations.AlterField(
            model_name="pmobjectmodel",
            name="isbn",
            field=models.CharField(
                help_text="کالا کد", max_length=13, verbose_name="شناسه بارکد"
            ),
        ),
    ]
