# Generated by Django 5.0 on 2023-12-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TellModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, verbose_name='شماره داخلی')),
                ('title', models.CharField(max_length=30, verbose_name='نام واحد')),
            ],
            options={
                'verbose_name': 'شماره تماس ها',
                'verbose_name_plural': 'شماره تماس',
            },
        ),
    ]
