# Generated by Django 5.0 on 2023-12-16 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tell', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tellmodel',
            options={'verbose_name': 'شماره تماس ', 'verbose_name_plural': ' شماره تماس ها'},
        ),
    ]
